# Default values for hzero-swagger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.cn-hangzhou.aliyuncs.com/hzero-hzero/hzero-swagger
  pullPolicy: Always

preJob:
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/dbtool:0.5.6
  timeout: 1200
  preInitDB:
    enable: true
    datasource:
      url: jdbc:mysql://192.168.11.167:3306/hzero_governance?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Root@1234!

deployment:
  managementPort: 8051

env:
  open:
    CHOERODON_EVENT_CONSUMER_KAFKA_BOOTSTRAP_SERVERS: 192.168.11.167:9092
    EUREKA_DEFAULT_ZONE: http://192.168.12.101:8000/eureka/
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    SPRING_DATASOURCE_URL: jdbc:mysql://192.168.11.167:3306/hzero_governance?useUnicode=true&characterEncoding=utf-8&useSSL=false
    SPRING_DATASOURCE_USERNAME: hzero
    SPRING_DATASOURCE_PASSWORD: hzero
    SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: 192.168.11.167:9092
    SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES: 192.168.11.167:2181
    SPRING_CLOUD_CONFIG_ENABLED: false
    SPRING_CLOUD_CONFIG_URI: http://192.168.12.101:8010/
    LOGGING_LVELE: debug

metrics:
  path: /prometheus
  group: spring-boot

logs:
 parser: spring-boot

persistence:
  enabled: false

service:
  enabled: false
  type: ClusterIP
  port: 8050
  name: hzero-swagger
  
ingress:
  enabled: false

resources:
  limits:
    memory: 2Gi
  requests:
    memory: 1.5Gi

